export const productsArr = [
  {
    product_Name: "Men Printed Hooded Neck Poly Cotton Navy Blue T-Shirt",
    product_id: "0001",
    brand: "Elitz",
    category: "Top-Wear",
    sub_category: "T-Shirts",
    gender: "Male",
    price: 300,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/kyxb9u80/t-shirt/o/i/u/xl-ziigzag-combo-hood-elitz-original-imagbfthh8hapeg7.jpeg",
      "https://rukminim2.flixcart.com/image/832/832/kyxb9u80/t-shirt/j/e/s/xl-ziigzag-combo-hood-elitz-original-imagbfthmhwh5qqm.jpeg",
      "https://rukminim2.flixcart.com/image/832/832/kyxb9u80/t-shirt/i/1/f/xl-ziigzag-combo-hood-elitz-original-imagbfthhprhh9qe.jpeg",
    ],
    rating: 2.4,
  },
  {
    product_Name: "Men Self Design Polo Neck Cotton Blend Maroon T-Shirt",
    product_id: "0002",
    brand: "KALT",
    category: "Top-Wear",
    sub_category: "T-Shirts",
    gender: "Male",
    price: 750,
    img: [
      "https://rukminim2.flixcart.com/image/128/128/t-shirt/d/y/d/m177-mm-kalt-4xl-original-imaebjdgn2xv2zgf.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/128/128/t-shirt/d/y/d/m177-mm-kalt-4xl-original-imaebjdgchsw8whq.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/128/128/t-shirt/d/y/d/m177-mm-kalt-4xl-original-imaebjdgh49vnst2.jpeg?q=70",
    ],
    rating: 4.1,
  },
  {
    product_Name: "Men Solid Round Neck Cotton Blend Black T-shirt",
    product_id: "0003",
    brand: "HighLander",
    category: "Top-Wear",
    sub_category: "T-Shirts",
    gender: "Male",
    price: 340,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/k70spzk0/t-shirt/9/w/c/m-hlts001156-black-highlander-original-imafpchr4u8kprnn.jpeg",
      "https://rukminim2.flixcart.com/image/832/832/k70spzk0/t-shirt/9/w/c/m-hlts001156-black-highlander-original-imafpchrmtxdrykm.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/k70spzk0/t-shirt/9/w/c/m-hlts001156-black-highlander-original-imafpchre4szs29z.jpeg?q=70",
    ],
    rating: 3.8,
  },
  {
    product_Name: "Ms Graphic V Men Solid Polo Neck Cotton Blend Red T-Shirt",
    product_id: "0004",
    brand: "PUMA",
    category: "Top-Wear",
    sub_category: "T-Shirts",
    gender: "Male",
    price: 701,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/l3lx8cw0/t-shirt/w/y/n/m-67026532-puma-original-imagezuzvnsxmebv.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/128/128/l3lx8cw0/t-shirt/h/k/4/m-67026532-puma-original-imagezuzswgtq87s.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/128/128/l3lx8cw0/t-shirt/y/k/x/m-67026532-puma-original-imagezuzyhrdkdky.jpeg?q=70",
    ],
    rating: 4.2,
  },
  {
    product_Name: "Men Striped, Printed Round Neck Cotton Blend White T-Shirt",
    product_id: "0005",
    brand: "FASHION 'N' STYLE",
    category: "Top-Wear",
    sub_category: "T-Shirts",
    gender: "Male",
    price: 413,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/o/q/2/l-wh-01-fashion-n-style-original-imagskrr2f4hsnje.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/4/l/b/l-wh-01-fashion-n-style-original-imagskrrff68eghz.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/o/5/s/l-wh-01-fashion-n-style-original-imagskrrkmq3bbsg.jpeg?q=70",
    ],
    rating: 2.2,
  },
  {
    product_Name: "Men Printed Round Neck Pure Cotton White T-Shirt",
    product_id: "0006",
    brand: "HRX by Hrithik Roshan",
    category: "Top-Wear",
    sub_category: "T-Shirts",
    gender: "Male",
    price: 313,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/m/f/l/l-22977220-hrx-by-hrithik-roshan-original-imagsw8zrnm8c5ma.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/q/v/z/l-22977220-hrx-by-hrithik-roshan-original-imagsw8zvzvzzk5h.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/1/8/g/l-22977220-hrx-by-hrithik-roshan-original-imagsw8zrwsmq73j.jpeg?q=70",
    ],
    rating: 3.2,
  },
  {
    product_Name: "Men Regular Fit Solid Spread Collar Formal Shirt",
    product_id: "0007",
    brand: "FIBERMILL",
    category: "Top-Wear",
    sub_category: "Shirts",
    gender: "Male",
    price: 389,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/k/g/1/l-fbrml-r-fibermill-original-imagjfk6ytwytyg3.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/m/i/i/l-fbrml-r-fibermill-original-imagjfk6jpjzurvr.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/d/f/g/l-fbrml-r-fibermill-original-imaghq4x6ftvzmhy.jpeg?q=70",
    ],
    rating: 4,
  },
  {
    product_Name: "Men Slim Fit Solid Formal Shirt",
    product_id: "0008",
    brand: "PARK AVENUE",
    category: "Top-Wear",
    sub_category: "Shirts",
    gender: "Male",
    price: 799,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/7/t/d/-original-imags43z5mkwqfym.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/u/j/h/-original-imags43zutzvyvsv.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/g/v/m/-original-imags43zgjasgmbt.jpeg?q=70",
    ],
    rating: 4.4,
  },
  {
    product_Name: "Men Slim Fit Solid Formal Shirt",
    product_id: "0009",
    brand: "ARROW",
    category: "Top-Wear",
    sub_category: "Shirts",
    gender: "Male",
    price: 1099,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/8/0/g/39-20308530-arrow-original-imagpu3fcpqj7x5z.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/0/f/b/44-20308530-arrow-original-imagpu32yncuuqtg.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/6/f/x/39-20308530-arrow-original-imagpu3fcfnfde84.jpeg?q=70",
    ],
    rating: 3.9,
  },
  {
    product_Name: "Men Regular Fit Checkered Button Down Collar Casual Shirt",
    product_id: "0010",
    brand: "ALY JOHN",
    category: "Top-Wear",
    sub_category: "Shirts",
    gender: "Male",
    price: 499,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/r/a/w/m-slate-lrc-06-aly-john-original-imags327rbq2bk6f.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/r/9/i/l-lrc-06-adwyn-peter-original-imagpxce6pga3dkf.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/9/b/u/l-lrc-06-adwyn-peter-original-imagpxcetc9kznbz.jpeg?q=70",
    ],
    rating: 3.6,
  },
  {
    product_Name: "Men Regular Fit Solid Cut Away Collar Casual Shirt",
    product_id: "0011",
    brand: "Allen Solly",
    category: "Top-Wear",
    sub_category: "Shirts",
    gender: "Male",
    price: 1049,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/q/l/m/40-assfqmofd89804-allen-solly-original-imafwhdffgpm9zuc-bb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kg6vfrk0-0/shirt/v/o/a/40-assfqmofd89804-allen-solly-original-imafwhdfdqt96new.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kg6vfrk0-0/shirt/a/s/r/40-assfqmofd89804-allen-solly-original-imafwhdfhhahhzp2.jpeg?q=70",
    ],
    rating: 3.9,
  },
  {
    product_Name: "Men Tailored Fit Solid Cut Away Collar Casual Shirt",
    product_id: "0012",
    brand: "U.S. POLO ASSN.",
    category: "Top-Wear",
    sub_category: "Shirts",
    gender: "Male",
    price: 879,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/7/w/v/m-usshto2295-u-s-polo-assn-original-imagsnwx4faguwfy.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/6/r/d/m-usshto2295-u-s-polo-assn-original-imagsnwxxa4u7vud.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/g/k/i/m-usshto2295-u-s-polo-assn-original-imagsnwxy9qkzccz.jpeg?q=70",
    ],
    rating: 4.4,
  },
  {
    product_Name: "Men Regular Mid Rise Light Green Jeans",
    product_id: "0013",
    brand: "STUDIO NEXX",
    category: "Bottom-Wear",
    sub_category: "Jeans",
    gender: "Male",
    price: 739,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/kms2j680/jean/z/s/m/30-blaze-darkolive-studio-nexx-original-imagfh5qkt7jfg5e.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kms2j680/jean/s/x/9/30-blaze-darkolive-studio-nexx-original-imagfh5qpgqfmgpx.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kms2j680/jean/p/i/w/30-blaze-darkolive-studio-nexx-original-imagfh5qmaphjtuq.jpeg?q=70",
    ],
    rating: 3.9,
  },
  {
    product_Name: "Men Slim Mid Rise Grey Jeans",
    product_id: "0014",
    brand: "Spykar",
    category: "Bottom-Wear",
    sub_category: "Jeans",
    gender: "Male",
    price: 1159,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/l2hwwi80/jean/2/q/r/34-ytkn01bb002ltgrey-spykar-original-imagdtwnruk9gwhx.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/l2hwwi80/jean/d/t/n/34-ytkn01bb002ltgrey-spykar-original-imagdtwnna7xf3fu.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/l2hwwi80/jean/6/s/6/34-ytkn01bb002ltgrey-spykar-original-imagdtwnftwubnqs.jpeg?q=70",
    ],
    rating: 3.8,
  },
  {
    product_Name: "Men Slim Mid Rise Black Jeans",
    product_id: "0015",
    brand: "HIGH LANDER",
    category: "Bottom-Wear",
    sub_category: "Jeans",
    gender: "Male",
    price: 732,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/k70spzk0/jean/f/a/g/30-hljn000765-highlander-original-imafpchx9c2gdxks.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/k70spzk0/jean/f/a/g/30-hljn000765-highlander-original-imafpchxhddugyvz.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/k70spzk0/jean/f/a/g/30-hljn000765-highlander-original-imafpchxtwvcw3dk.jpeg?q=70",
    ],
    rating: 3.8,
  },
  {
    product_Name: "Men Regular Fit White Cotton Blend Trousers",
    product_id: "0016",
    brand: "Roadster",
    category: "Bottom-Wear",
    sub_category: "Trousers",
    gender: "Male",
    price: 827,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/z/6/b/30-6817877-roadster-original-imafgmq7nsjwrgrz-bb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/jvtujrk0/trouser/z/6/b/32-6817877-roadster-original-imafgmq7gcrxsyc2.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/jvtujrk0/trouser/z/6/b/34-6817877-roadster-original-imafgmq7st8fnafy.jpeg?q=70",
    ],
    rating: 4.2,
  },
  {
    product_Name: "Men Regular Fit Grey Cotton Blend Trousers",
    product_id: "0017",
    brand: "U.S. POLO ASSN.",
    category: "Bottom-Wear",
    sub_category: "Trousers",
    gender: "Male",
    price: 1295,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/l/p/n/50-ustro0564-u-s-polo-assn-original-imagnssgv2kcrwtz.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/q/9/n/50-ustro0564-u-s-polo-assn-original-imagnssgzczsunjn.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/t/o/j/50-ustro0564-u-s-polo-assn-original-imagnssgak9xqpup.jpeg?q=70",
    ],
    rating: 4.2,
  },
  {
    product_Name: "Men Slim Fit Blue Pure Cotton Trousers",
    product_id: "0018",
    brand: "The Indian Garage Co.",
    category: "Bottom-Wear",
    sub_category: "Trousers",
    gender: "Male",
    price: 569,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/0/w/w/-original-imagngz2z4wbzuzb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/w/a/o/-original-imagngz2aquyyypb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/a/q/p/-original-imagngz2vzctujts.jpeg?q=70",
    ],
    rating: 3.4,
  },
  {
    product_Name: "Men Cargos",
    product_id: "0019",
    brand: "The Indian Garage Co.",
    category: "Bottom-Wear",
    sub_category: "Cargo",
    gender: "Male",
    price: 629,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/cargo/0/h/f/-original-imaggyetwkhmxypu.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/cargo/k/d/x/-original-imaggyet4encnz6x.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/cargo/o/i/c/-original-imaggyets5se7tqa.jpeg?q=70",
    ],
    rating: 3.9,
  },
  {
    product_Name: "Men Cargos",
    product_id: "0020",
    brand: "TRIPR",
    category: "Bottom-Wear",
    sub_category: "Cargo",
    gender: "Male",
    price: 299,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/cargo/q/3/q/l-tgyjog-cargo14-tripr-original-imagsbuq6qw6ezah.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/cargo/c/a/q/xs-tgyjog-cargo12-tripr-original-imags8vhjhgukvb2.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/cargo/y/o/t/3xl-togrjog-cargo15-tripr-original-imagsbuqhrfgpzcu.jpeg?q=70",
    ],
    rating: 3.9,
  },
  {
    product_Name: "Men Cargos",
    product_id: "0021",
    brand: "HIGH LANDER",
    category: "Bottom-Wear",
    sub_category: "Cargo",
    gender: "Male",
    price: 790,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/0/1/z/36-hltr004955-highlander-original-imaggkqhne8cjxfy.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/7/c/p/36-hltr004955-highlander-original-imaggkqhvq9cqhpn.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/n/d/q/36-hltr004955-highlander-original-imaggkqhukmbudhj.jpeg?q=70",
    ],
    rating: 4.1,
  },
  {
    product_Name: "Casual Regular Sleeves Printed Women Blue Top",
    product_id: "0022",
    brand: "Yash Gallery",
    category: "Western Wear",
    sub_category: "Tops",
    gender: "Female",
    price: 699,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/top/d/e/g/xl-1-1057ykblue-yash-gallery-original-imagryfya4pyzcx5.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/top/n/u/w/xl-1-1057ykblue-yash-gallery-original-imagryfyxw5psmgf.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/top/j/m/9/xl-1-1057ykblue-yash-gallery-original-imagryfycpjbzqzc.jpeg?q=70",
    ],
    rating: 4.1,
  },
  {
    product_Name: "Casual Regular Sleeves Self Design Women Green Top",
    product_id: "0023",
    brand: "PLUSS",
    category: "Western Wear",
    sub_category: "Tops",
    gender: "Female",
    price: 2199,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/top/m/v/1/s-ltp16317-tealgreen-pluss-original-imagzdzxzzfgj2vc.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/top/n/f/i/4xl-ltp16317-tealgreen-pluss-original-imagzdzxam8uewg8.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/top/b/i/2/4xl-ltp16317-tealgreen-pluss-original-imagzdzx2nmebv2p.jpeg?q=70",
    ],
    rating: 4.0,
  },
  {
    product_Name: "Women Regular Fit Solid Spread Collar Casual Shirt",
    product_id: "0024",
    brand: "MARKS & SPENCER",
    category: "Western Wear",
    sub_category: "Tops",
    gender: "Female",
    price: 790,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/k/l/4/m-t435603kseafoam-marks-spencer-original-imagmg5mjbajqukt.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/w/b/w/m-t435603kseafoam-marks-spencer-original-imagmg5mzyayywby.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/l/0/q/m-t435603kseafoam-marks-spencer-original-imagmg5m73hzvdf4.jpeg?q=70",
    ],
    rating: 3.7,
  },
  {
    product_Name: "Women A-line Dark Blue, Blue Dress",
    product_id: "0025",
    brand: "Glamoda",
    category: "Western Wear",
    sub_category: "Dresses",
    gender: "Female",
    price: 868,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/8/t/m/xl-gd-008-light-blue-glamoda-original-imagpn9fwwhdfkgw.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/f/n/j/l-gd-002-dark-blue-glamoda-original-imagpn9fsw733qa6.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/y/j/l/l-women-a-line-light-blue-dress-glamoda-original-imagsz62czgbajg6.jpeg?q=70",
    ],
    rating: 4.2,
  },
  {
    product_Name: "Women Asymmetric Yellow Dress",
    product_id: "0026",
    brand: "AND",
    category: "Western Wear",
    sub_category: "Dresses",
    gender: "Female",
    price: 1500,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/k6jnfrk0/dress/j/z/s/xxl-ss20an122drb72-and-original-imafzzhaty79zhzp.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/k6jnfrk0/dress/j/z/s/xl-ss20an122drb72-and-original-imafzzhaa2ujhczh.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/k6jnfrk0/dress/j/z/s/xxl-ss20an122drb72-and-original-imafzzhapgm9rswc.jpeg?q=70",
    ],
    rating: 3.6,
  },
  {
    product_Name: "Women Boot-Leg High Rise Light Blue, White Jeans",
    product_id: "0027",
    brand: "AND",
    category: "Western Wear",
    sub_category: "Jeans",
    gender: "Female",
    price: 999,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/n/t/5/34-gtsladiesjeans200-guti-original-imags2ec5huscy2w.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/u/v/5/34-gtsladiesjeans200-guti-original-imags2ectptmdmzw.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/c/i/i/30-gtsladiesjeans198-guti-original-imags2ecjxy96ugu.jpeg?q=70",
    ],
    rating: 3.1,
  },
  {
    product_Name: "Women Skinny Mid Rise Dark Blue Jeans",
    product_id: "0028",
    brand: "Roadster",
    category: "Western Wear",
    sub_category: "Jeans",
    gender: "Female",
    price: 559,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/g/y/7/30-8803817-roadster-original-imafjwpcbshcn9zs-bb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/k0463rk0/jean/g/y/7/30-8803817-roadster-original-imafjwpczf6ygxkm.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/k0463rk0/jean/g/y/7/30-8803817-roadster-original-imafjwpcyjvkfgcn.jpeg?q=70",
    ],
    rating: 3.8,
  },
  {
    product_Name: "Solid Women Maroon Casual Shorts",
    product_id: "0029",
    brand: "Roadster",
    category: "Western Wear",
    sub_category: "Shorts",
    gender: "Female",
    price: 399,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/night-suit/j/k/9/xxl-re-01ns-maroon-rakshika-enterprises-original-imagsnd5v3h7k2fb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/night-suit/y/q/p/xxl-re-01ns-maroon-rakshika-enterprises-original-imagsnd5uuv6sw7v.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/night-suit/o/u/e/m-re-01ns-green-rakshika-enterprises-original-imagsnd5nagyrtkm.jpeg?q=70",
    ],
    rating: 3.1,
  },
  {
    product_Name: "Checkered Women Black Regular Shorts",
    product_id: "0030",
    brand: "KLART",
    category: "Western Wear",
    sub_category: "Shorts",
    gender: "Female",
    price: 254,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/l2arp8w0/short/y/k/2/xl-1pk-4-black-pack1-klart-original-imagdzkg9gh2j8md.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/l2arp8w0/short/v/d/p/xl-1pk-4-black-pack1-klart-original-imagdzkgyzbtgyme.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/l2arp8w0/short/c/9/y/m-2pk-12-black-pack2-klart-original-imagdzkggaz5xgjy.jpeg?q=70",
    ],
    rating: 3.3,
  },
  {
    product_Name: "3BUTTERFLIES Black Jegging  (Solid)",
    product_id: "0031",
    brand: "3BUTTERFLIES",
    category: "Western Wear",
    sub_category: "Jeggings",
    gender: "Female",
    price: 468,
    img: [
      "https://rukminim2.flixcart.com/image/416/416/xif0q/jegging/s/w/y/32-fpblk-l-32-3butterflies-original-imagajvetbvnvmdk-bb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/kyag87k0/jegging/f/8/i/32-fpblk-l-32-3butterflies-original-imagajvecnerpjnq.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/kyag87k0/jegging/o/g/x/32-fpblk-l-32-3butterflies-original-imagajvebg8z7jn9.jpeg?q=70",
    ],
    rating: 4.1,
  },
  {
    product_Name: "Color Block Women Grey Tights",
    product_id: "0032",
    brand: "Neu Look",
    category: "Western Wear",
    sub_category: "Jeggings",
    gender: "Female",
    price: 539,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/kjx6tu80/tight/p/e/f/l-gt-08-neu-look-original-imafzdsekxwzebgm.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kjx6tu80/tight/w/5/y/l-gt-08-neu-look-original-imafzdsevjugmmbr.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kjx6tu80/tight/l/h/x/l-gt-08-neu-look-original-imafzdsekftzgyyc.jpeg?q=70",
    ],
    rating: 3.3,
  },
  {
    product_Name: "Women Relaxed Cream Polyester Trousers",
    product_id: "0033",
    brand: "Aahwan",
    category: "Western Wear",
    sub_category: "Trousers",
    gender: "Female",
    price: 699,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/j/w/l/28-220-offwhite-aahwan-original-imagzjfjk5bbcsnd.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/d/9/g/28-220-offwhite-aahwan-original-imagzjfjhmzsqx8s.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/b/y/7/28-220-offwhite-aahwan-original-imagzjfjtdnymhgr.jpeg?q=70",
    ],
    rating: 3.5,
  },
  {
    product_Name: "Women Regular Fit Green Cotton Blend Trousers",
    product_id: "0034",
    brand: "KOTTY",
    category: "Western Wear",
    sub_category: "Trousers",
    gender: "Female",
    price: 649,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/x/r/k/32-kottywomenspant415-kotty-original-imagpaymbhfzetpb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/5/t/f/32-kottywomenspant415-kotty-original-imagpaympd3gnty8.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/y/a/t/32-kottywomenspant415-kotty-original-imagpaymwszvfpdu.jpeg?q=70",
    ],
    rating: 4.3,
  },
  {
    product_Name: "Woven Tant Pure Cotton Saree  (Green)",
    product_id: "0035",
    brand: "WoodenTant",
    category: "Ethnic Wear",
    sub_category: "Sarees",
    gender: "Female",
    price: 699,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sari/y/k/b/free-wcs209-woodentant-no-blouse-original-imaghy6g443jcjvb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sari/u/l/o/free-wcs209-woodentant-no-blouse-original-imaghy6gzhfvjhav.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sari/n/i/j/free-wcs209-woodentant-no-blouse-original-imaghy6gbghnhary.jpeg?q=70",
    ],
    rating: 3.8,
  },
  {
    product_Name: "Woven Bandhani Silk Blend Saree  (Multicolor)",
    product_id: "0036",
    brand: "Divastri",
    category: "Ethnic Wear",
    sub_category: "Sarees",
    gender: "Female",
    price: 3099,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sari/p/y/n/free-2ashima203-div-divastri-unstitched-original-imagsw44t7yeyuhf.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sari/8/i/n/free-2ashima203-div-divastri-unstitched-original-imagsw447ahh5tfj.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sari/4/5/a/free-2ashima203-div-divastri-unstitched-original-imagsw4497feftzu.jpeg?q=70",
    ],
    rating: 3.8,
  },
  {
    product_Name:
      "Women Floral Print Cotton Rayon Anarkali Kurta With Attached Dupatta  (Blue)",
    product_id: "0037",
    brand: "Skyasia ",
    category: "Ethnic Wear",
    sub_category: "Kurtas & Kurthis",
    gender: "Female",
    price: 769,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/q/o/h/3xl-sky-348bluefloralkpdset-new-stylish-original-imagrb7ras4v3cqb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/y/j/8/3xl-sky-348bluefloralkpdset-new-stylish-original-imagrb7rxzp9tys8.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/f/e/8/xl-sky-348bluefloralkpdset-skyasia-original-imagrb8arcuafbee.jpeg?q=70",
    ],
    rating: 4.4,
  },
  {
    product_Name: "Women Embroidered Pure Cotton Anarkali Kurta  (White)",
    product_id: "0038",
    brand: "Jaipur Threads ",
    category: "Ethnic Wear",
    sub_category: "Kurtas & Kurthis",
    gender: "Female",
    price: 1349,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/i/i/b/3xl-sscgwn0003-jaipur-threads-original-imagznh8gtkkwkzu.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/8/3/4/3xl-sscgwn0003-jaipur-threads-original-imagznh8tqjpwasy.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/i/i/f/3xl-sscgwn0003-jaipur-threads-original-imagzwgt8j36txff.jpeg?q=70",
    ],
    rating: 4.2,
  },
  {
    product_Name: "Unstitched Chanderi Cotton Salwar Suit Material Embroidered",
    product_id: "0039",
    brand: "VORIMA ",
    category: "Ethnic Wear",
    sub_category: "Dress Materials",
    gender: "Female",
    price: 1349,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/kwqq1zk0/fabric/m/5/v/yes-2-25-m-unstitched-2-2-m-jennifer-laxify-store-original-imag9cvys7gqhwsz.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kwqq1zk0/fabric/z/f/i/yes-2-25-m-unstitched-2-2-m-jennifer-laxify-store-original-imag9cvyzqhamjhr.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kwqq1zk0/fabric/m/5/v/yes-2-25-m-unstitched-2-2-m-jennifer-laxify-store-original-imag9cvys7gqhwsz.jpeg?q=70",
    ],
    rating: 4.2,
  },
  {
    product_Name: "Unstitched Cotton Blend Salwar Suit Material Embellished",
    product_id: "0040",
    brand: "Hani synthetics ",
    category: "Ethnic Wear",
    sub_category: "Dress Materials",
    gender: "Female",
    price: 612,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/kxf0jgw0/fabric/j/o/1/yes-2-35-m-unstitched-2-2-m-30hd-sanhani-original-imag9vg8pf8yqwph.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kxf0jgw0/fabric/a/b/t/yes-2-35-m-unstitched-2-2-m-30hd-sanhani-original-imag9vgggpps7mya.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kxf0jgw0/fabric/c/o/q/yes-2-35-m-unstitched-2-2-m-30hd-sanhani-original-imag9vg6husnbuqr.jpeg?q=70",
    ],
    rating: 3.7,
  },
  {
    product_Name: "Embroidered Semi Stitched Lehenga Choli  (Blue)",
    product_id: "0041",
    brand: "GOROLY ",
    category: "Ethnic Wear",
    sub_category: "Lehenga Choli",
    gender: "Female",
    price: 724,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/lehenga-choli/v/t/v/free-3-4-sleeve-future-lehenga-choli-navya-creation-original-imagnw2wgt2umab9.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/lehenga-choli/s/u/0/free-3-4-sleeve-future-lehenga-choli-navya-creation-original-imagnw2wjvthbnha.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/lehenga-choli/l/e/p/free-3-4-sleeve-future-lehenga-choli-navya-creation-original-imagnw2wdvztjjku.jpeg?q=70",
    ],
    rating: 4.1,
  },
  {
    product_Name: "Embroidered Semi Stitched Lehenga Choli  (Light Blue)",
    product_id: "0042",
    brand: "NIYAMI ",
    category: "Ethnic Wear",
    sub_category: "Lehenga Choli",
    gender: "Female",
    price: 1593,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/lehenga-choli/l/d/r/free-short-sleeve-shagun-lehenga-kr-royalwish-original-imagc4s3upwzzpxk.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/lehenga-choli/j/1/2/free-short-sleeve-shagun-lehenga-kr-royalwish-original-imagbtstzrpfg9tv.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/lehenga-choli/t/4/g/free-short-sleeve-shagun-lehenga-kr-royalwish-original-imagbtstmkhcy6jz.jpeg?q=70",
    ],
    rating: 4.0,
  },
  {
    product_Name: "Boat Neck Women Blouse",
    product_id: "0043",
    brand: "Oomph!",
    category: "Ethnic Wear",
    sub_category: "Blouse",
    gender: "Female",
    price: 1169,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/kjq1mkw0-0/blouse/v/8/z/m-rbbl17-oomph-original-imafz85zzwmzphyf.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kjq1mkw0-0/blouse/3/c/t/m-rbbl17-oomph-original-imafz85zbmcuf5fe.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kjq1mkw0-0/blouse/v/j/h/m-rbbl17-oomph-original-imafz85zt5k4fasv.jpeg?q=70",
    ],
    rating: 4.0,
  },
  {
    product_Name: "Round Neck Women Blouse",
    product_id: "0044",
    brand: "abhisa",
    category: "Ethnic Wear",
    sub_category: "Blouse",
    gender: "Female",
    price: 539,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/l09w8sw0/blouse/h/u/k/36-2007-abhisa-original-imagc3fe23ugsa3e.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/l09w8sw0/blouse/c/h/b/36-2007-abhisa-original-imagc3fe6g6zfdxh.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/l09w8sw0/blouse/l/f/j/42-2009-abhisa-original-imagc3fekceg8dqa.jpeg?q=70",
    ],
    rating: 4.0,
  },
  {
    product_Name: "Women Viscose Rayon Kurti Pant Set",
    product_id: "0045",
    brand: "Rangreal",
    category: "Ethnic Wear",
    sub_category: "Kurta Sets",
    gender: "Female",
    price: 539,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/l5jxt3k0/ethnic-set/v/a/n/m-pinkzariset-styleit-original-imagg79cxzqhqkrq.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/l5jxt3k0/ethnic-set/d/b/v/m-pinkzariset-styleit-original-imagg79cpzpqgq5v.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/l5jxt3k0/ethnic-set/h/1/l/m-pinkzariset-styleit-original-imagg79cw8kfgfpg.jpeg?q=70",
    ],
    rating: 4.6,
  },
  {
    product_Name: "Women Silk Blend Kurta Trouser Set",
    product_id: "0046",
    brand: "LIBAS",
    category: "Ethnic Wear",
    sub_category: "Kurta Sets",
    gender: "Female",
    price: 2799,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/q/v/o/l-38037o-libas-original-imagpea37gjvk4nx.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/r/1/j/l-38037o-libas-original-imagpea37ynzbawn.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/v/x/x/l-38037o-libas-original-imagpea3gstyvbe5.jpeg?q=70",
    ],
    rating: 4.6,
  },
  {
    product_Name: "Embroidered Georgette Stitched Anarkali Gown  (Purple)",
    product_id: "0047",
    brand: "Elegantik ",
    category: "Ethnic Wear",
    sub_category: "Gowns",
    gender: "Female",
    price: 1249,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/gown/g/m/q/192-xxl-full-sleeve-stitched-nanditaa-elegantik-600-original-imagsbzu6dtrwnze.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/gown/v/q/i/192-xxl-full-sleeve-stitched-nanditaa-elegantik-600-original-imagsbzuayrbvehx.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/gown/5/6/z/192-xxl-full-sleeve-stitched-nanditaa-elegantik-600-original-imagsbzur9xfkcs5.jpeg?q=70",
    ],
    rating: 4.2,
  },
  {
    product_Name: "Embroidered Georgette Stitched Flared/A-line Gown  (Green)",
    product_id: "0048",
    brand: "Ethnic Yard",
    category: "Ethnic Wear",
    sub_category: "Gowns",
    gender: "Female",
    price: 1301,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/gown/b/s/p/na-m-full-sleeve-stitched-e6014-ethnic-yard-na-original-imagzyds56uyt75a.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/gown/u/n/a/na-xl-full-sleeve-stitched-e6014-afsana-na-original-imagnqezgggqavqs.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/gown/z/w/c/na-m-full-sleeve-stitched-e6014-afsana-na-original-imagnqezupc25b9u.jpeg?q=70",
    ],
    rating: 4.2,
  },
  {
    product_Name: "Silk Blend Printed Green Women Dupatta",
    product_id: "0049",
    brand: "DUPATTA BAZAAR",
    category: "Ethnic Wear",
    sub_category: "Dupattas",
    gender: "Female",
    price: 699,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/k3q76a80/dupatta/p/a/z/na-2-4-meters-db1789-dupatta-bazaar-na-original-imafmskzmdsz2huf.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/k3q76a80/dupatta/p/a/z/na-2-4-meters-db1789-dupatta-bazaar-na-original-imafmskzkvhrhefj.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/k3q76a80/dupatta/p/a/z/na-2-4-meters-db1789-dupatta-bazaar-na-original-imafmskzwy9sdfaj.jpeg?q=70",
    ],
    rating: 4.2,
  },
  {
    product_Name: "Cotton Blend Self Design Multicolor Women Dupatta",
    product_id: "0050",
    brand: "wearswadeshi",
    category: "Ethnic Wear",
    sub_category: "Dupattas",
    gender: "Female",
    price: 699,
    img: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/dupatta/d/z/o/2-5-meters-1-wrdppt02-wearswadeshi-original-imagr558zeefyq2z.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/dupatta/n/i/z/2-5-meters-1-wrdppt02-wearswadeshi-original-imagr558yx9fjhzk.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/dupatta/h/j/r/2-5-meters-1-wrdppt02-wearswadeshi-original-imagr5587yd3ctch.jpeg?q=70",
    ],
    rating: 4.6,
  },
];
